version: 2

project_name: modelfs

# Build configuration
builds:
  - id: manager
    binary: manager
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}


# Archive configuration
archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

# Docker images configuration (disabled; handled by GitHub Actions)
dockers_v2: []

# GitHub release configuration
release:
  mode: replace
  header: |
    ## {{ .ProjectName }} {{ .Tag }}
  footer: |
    ---
    
    Full Changelog: {{ .PreviousTag }}...{{ .Tag }}

# Changelog configuration
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
  groups:
    - title: Features
      regexp: "^.*feat.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix.*$"
      order: 10
    - title: Other Changes
      order: 999

# Snapshots configuration
snapshot: {}

# Checksums configuration
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256
