# GoReleaser configuration for modelfs
version: 2

project_name: modelfs

# Build configuration
builds:
  - id: manager
    binary: manager
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

# Archive configuration
archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

# Docker images configuration
dockers_v2:
  - images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/modelfs"
    tags:
      - "{{ .Tag }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile

# GitHub release configuration
release:
  mode: replace
  header: |
    ## {{ .ProjectName }} {{ .Tag }}
    
    {{ .Changelog }}
  footer: |
    ---
    
    Full Changelog: {{ .PreviousTag }}...{{ .Tag }}

# Changelog configuration
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

# Snapshots configuration
snapshot: {}

# Checksums configuration
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

